package state;

public interface ClientControllable extends Controllable 
{
	/**
	 * Function to allow the initialisation of a GameState using dynamic filenames
	 * The idea is is that the files will be downloaded from the server, saved and the
	 * filenames passed to this intreface to load them
	 * @param mapFilename The filename of the map image
	 * @param graphFilename The filename of the graph text file
	 * @param positionsFilename The filename of the node location text file
	 * @param gameFilename The filename of the game text file. This file is generated by
	 * dumping the contents of the database into a file. This file is then passed to the loadGame function
	 * to initialise the game state in the same configuration as on the server
	 * @return If initalisation was a success
	 */
	public Boolean initialiseGame(String mapFilename, String graphFilename, 
			String positionsFilename, String gameFilename);
}
